apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: lamp-dev
  labels:
    app: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: reTsec132409
  MYSQL_DATABASE: webAppDB
  MYSQL_USER: dbconnect
  MYSQL_PASSWORD: 1239ni22md
